if: branch IN (master, testing) OR tag IS present

unused: &linux-template
  os: linux
  dist: trusty
  language: cpp
  services: docker
  sudo: required
  before_install:
    - docker build -t eos:${DOCKER_TARGET} -f .travis/${DOCKER_TARGET} .
  script:
    - >
       docker run -it -e COVERALLS_TOKEN -e GITHUB_TOKEN -e PACKAGECLOUD_TOKEN eos:${DOCKER_TARGET}
       /bin/bash /src/.travis/build-and-test.bash ${DOCKER_TARGET} ${DOCKER_CXX} "${TRAVIS_TAG}" ${DOCKER_USE}

matrix:
  include:
    - <<: *linux-template
      env:
        - DOCKER_TARGET=xenial DOCKER_CXX=g++          DOCKER_USE=coverage

    - <<: *linux-template
      env:
        - DOCKER_TARGET=xenial DOCKER_CXX=g++          DOCKER_USE=deploy

    - <<: *linux-template
      env:
        - DOCKER_TARGET=xenial DOCKER_CXX=g++          DOCKER_USE=distcheck

    - <<: *linux-template
      env:
        - DOCKER_TARGET=xenial DOCKER_CXX=clang++-4.0  DOCKER_USE=distcheck

    - <<: *linux-template
      env:
        - DOCKER_TARGET=bionic DOCKER_CXX=g++          DOCKER_USE=deploy

    - <<: *linux-template
      env:
        - DOCKER_TARGET=bionic DOCKER_CXX=g++          DOCKER_USE=distcheck

    - <<: *linux-template
      env:
        - DOCKER_TARGET=disco  DOCKER_CXX=g++          DOCKER_USE=deploy

    - os: osx
      osx_image: xcode11
      language: cpp
      sudo: required
      before_install:
        - export HOMEBREW_LOGS=/tmp
        - brew tap eos/eos
        - brew outdated python || brew upgrade python || true
        - brew unlink python@2
        - rm -Rf '/usr/local/lib/python2.7/site-packages/numpy/'
        - brew outdated boost || brew upgrade boost || true
        - brew outdated boost-python3 || brew upgrade boost-python3 || true
        - brew install autoconf boost-python3 gsl hdf5 libtool minuit2 pmclib yaml-cpp
        - pip3 install h5py matplotlib scipy PyYAML
      script:
        - /bin/bash .travis/build-and-test.bash osx g++ "${TRAVIS_TAG}" test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5f1a75fe069428b1cd1
    on_success: change
    on_failure: always
    on_start: never
